// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9TgtwehxoLFM5hsPPu5kPiFI_u-vj8gU',
    appId: '1:564999756871:web:66722d16096fac3790a562',
    messagingSenderId: '564999756871',
    projectId: 'firelightsyncignitionapp',
    authDomain: 'firelightsyncignitionapp.firebaseapp.com',
    storageBucket: 'firelightsyncignitionapp.appspot.com',
    measurementId: 'G-2FHCN6N12C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY27o1xHo-0vO9MIFNHoHECaSm6dy8fk4',
    appId: '1:564999756871:android:f121494f25e390f190a562',
    messagingSenderId: '564999756871',
    projectId: 'firelightsyncignitionapp',
    storageBucket: 'firelightsyncignitionapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwvznbgwr7uBEWNUxIiAWGEeNS1yZ0lyc',
    appId: '1:564999756871:ios:609ff043d2d4241b90a562',
    messagingSenderId: '564999756871',
    projectId: 'firelightsyncignitionapp',
    storageBucket: 'firelightsyncignitionapp.appspot.com',
    iosBundleId: 'com.example.firelightsyncIgnitionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwvznbgwr7uBEWNUxIiAWGEeNS1yZ0lyc',
    appId: '1:564999756871:ios:c1e06b00b15b8f0990a562',
    messagingSenderId: '564999756871',
    projectId: 'firelightsyncignitionapp',
    storageBucket: 'firelightsyncignitionapp.appspot.com',
    iosBundleId: 'com.example.firelightsyncIgnitionapp.RunnerTests',
  );
}
