// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUi3UNcCz0yYF_jJASU9bSKJuPfcLQYIU',
    appId: '1:930989100046:web:9bc5b9723b323ec5b2805f',
    messagingSenderId: '930989100046',
    projectId: 'fluttoriot',
    authDomain: 'fluttoriot.firebaseapp.com',
    storageBucket: 'fluttoriot.appspot.com',
    measurementId: 'G-FLBPF012CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfnivpNmPqGsqIDfpUhNhklhMphqFwKwo',
    appId: '1:930989100046:android:58f9a71079d8345eb2805f',
    messagingSenderId: '930989100046',
    projectId: 'fluttoriot',
    storageBucket: 'fluttoriot.appspot.com',
  );
}
